version: '3.9'
services:
  postDB:
    container_name : PostDB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: postgres
    volumes :
      - database-data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped


volumes:
  database-data:

networks:
  postgres :
    driver : bridge

